### ISSUE TITLE
Issue applying patch

### ISSUE THREAD

**Issue by ph1lt0r** [azerothcore/mod-solo-lfg#10]
git apply modules/mod-solo-lfg/lfg-solo.patch
error: patch failed: src/server/game/DungeonFinding/LFGMgr.h:534
error: src/server/game/DungeonFinding/LFGMgr.h: patch does not apply

**Comment by cyberconan** [comment]
Hi!
This error happens to me:
Scanning dependencies of target scripts
[ 36%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/__/__/__/GenLoader.cpp.o
[ 36%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-solo-lfg/src/Lfg_Solo.cpp.o
/home/karl/Software/servers/azerothcore-wotlk/modules/mod-solo-lfg/src/Lfg_Solo.cpp:44:27: fatal error: no member named 'IsSoloLFG' in 'lfg::LFGMgr'
            if (!sLFGMgr->IsSoloLFG())
                 ~~~~~~~  ^
1 error generated.
Regards!

**Comment by cyberconan** [comment]
Sorry, was my fault, I didn't apply the patch. Regards!
