### ISSUE TITLE
Patch broken since last Update/Commit of azerothcore

### ISSUE THREAD

**Issue by jpaechnatz** [azerothcore/mod-solo-lfg#12]
After an update to the current commit of azerothcore, apply the patch in docker doesn't work any more.

error: patch failed: src/Lfg_Solo.cpp:20
error: src/Lfg_Solo.cpp: patch does not apply

Thanks for advise ;-)

**Comment by rogerc66** [comment]
Even patch the file manully, it wont compile successfully due to recent guid change, need an update pls

**Comment by Artanisx** [comment]
Hello
I just wanted to say this problem is still present even in the non-docker version.

Thanks!

**Comment by jpaechnatz** [comment]
Confirmed. I moved from docker to compiled/dashboard Version....

**Comment by Artanisx** [comment]
I did the same, and trying to install this failed sadly.

**Comment by nolt** [comment]
I have this error:

```
error: patch failed: src/server/game/DungeonFinding/LFGMgr.h:534
error: src/server/game/DungeonFinding/LFGMgr.h: patch does not apply
error: patch failed: src/server/game/DungeonFinding/LFGQueue.cpp:386
error: src/server/game/DungeonFinding/LFGQueue.cpp: patch does not apply
```

AC rev: https://github.com/azerothcore/azerothcore-wotlk/commit/f8b817a8fef40cc4f66ef534f1a15d7c7ab0808f

**Comment by locus313** [comment]
Thanks for confirming @jpaechnatz 
Issue resolved from https://github.com/azerothcore/mod-solo-lfg/pull/14
