### ISSUE TITLE
Failed to compile in VS2019

### ISSUE THREAD

**Issue by rhinjard** [azerothcore/mod-solo-lfg#17]
The module failed to compile in VS2019 with the errors
`
D:\AzerothCore\source\azerothcore-wotlk\modules\mod-solo-lfg\src\Lfg_Solo.cpp(44,27): error C2039: 'IsSoloLFG': is not a member of 'lfg::LFGMgr'
D:\AzerothCore\source\azerothcore-wotlk\src\server\game\DungeonFinding\LFGMgr.h(396): message : see declaration of 'lfg::LFGMgr'
D:\AzerothCore\source\azerothcore-wotlk\modules\mod-solo-lfg\src\Lfg_Solo.cpp(46,22): error C2039: 'ToggleSoloLFG': is not a member of 'lfg::LFGMgr'
D:\AzerothCore\source\azerothcore-wotlk\src\server\game\DungeonFinding\LFGMgr.h(396): message : see declaration of 'lfg::LFGMgr'

`

**Comment by Remberance** [comment]
same problem occured when i build this mod in vs 2019 v16.10.1.

**Comment by Valoriaz** [comment]
Apply lfg-solo.patch to your core.
In order to do this, please go to the root /azerothcore-wotlk of your installation.

 `Then do git apply modules/mod-solo-lfg/lfg-solo.patch `

**Comment by Remberance** [comment]
> Apply lfg-solo.patch to your core.
> In order to do this, please go to the root /azerothcore-wotlk of your installation.
> Then do `git apply modules/mod-solo-lfg/lfg-solo.patch `

thanks, worked.

**Comment by rhinjard** [comment]
Thanks, the issue was that the patch was not getting applied properly. But with recent commits, the patch worked.
