### ISSUE TITLE
Docker - Error building acore

### ISSUE THREAD

**Issue by Bandobras84** [azerothcore/mod-solo-lfg#22]
I'm getting an error, when attempting to rebuild acore after applying the patch after using git pull origin master.
After patching I'm starting ./acore.sh docker build but it says that the size of the precompiled header changed. I tried deleting the  whole /var-forlder and using build:nocache... but no success. Now I'm running out of ideas.
Can someone help me?

```
fatal error: file '/azerothcore/src/server/game/DungeonFinding/LFGMgr.h' has been modified since the precompiled header '/azerothcore/var/build/obj/src/server/scripts/CMakeFiles/scripts.dir/cmake_pch.hxx.pch' was built: size changed
note: please rebuild precompiled header '/azerothcore/var/build/obj/src/server/scripts/CMakeFiles/scripts.dir/cmake_pch.hxx.pch'
1 error generated.
make[2]: *** [src/server/scripts/CMakeFiles/scripts.dir/build.make:394: src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_lfg.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1162: src/server/scripts/CMakeFiles/scripts.dir/all] Error 2
```

**Comment by pangolp** [comment]
I am not sure, but I believe that this problem should not currently occur, if that is the case, I ask you to please make a new issue, providing as much information as possible, so that a developer can review it and try to fix it. Thank you.
