### ISSUE TITLE
Compile fail

### ISSUE THREAD

**Issue by Dude100** [azerothcore/mod-solo-lfg#27]
see https://github.com/azerothcore/mod-transmog/issues/54

**Comment by pangolp** [comment]
> see [azerothcore/mod-transmog#54](https://github.com/azerothcore/mod-transmog/issues/54)

The module was recently updated, so there should be no problem updating it. If the problem persists, I ask you to re-create another issue, and provide us with a little more information, which will help us to solve the problem.
