### ISSUE TITLE
Bug: 'You do not have the World of Warcraft expansion'

### ISSUE THREAD

**Issue by LiteWesteros** [azerothcore/mod-solo-lfg#44]
### Current Behaviour

The LFG tool displays the message "You do not have the World of Warcraft expansion" for every dungeon.
![image](https://github.com/user-attachments/assets/5129a129-437e-4483-a645-1971c7e4f9e9)
![image](https://github.com/user-attachments/assets/2cfaf552-cf27-4e15-b604-a8a87bb1a3d9)
The issue happens with player-bots also (here Gorrette is a playerbot):
![image](https://github.com/user-attachments/assets/b74efbd7-3826-420c-8f21-9b292dd09a2a)

### Expected Behaviour

Upon opening the LFG tool, I should be able to enter any dungeon given that I have the character requirements.

### Steps to reproduce the problem

1. Compile Azeroth Core Playerbot
2. Setup db and auth/world
3. Create an account with gmlevel 3, expansion value of account table set to 2. (0, 1 show no dungeons in LFG tool)
4. Use LFG tool

### AC rev. hash/commit

AzerothCore rev. 414805e692ab 2024-09-04 23:46:34 +0800 (Playerbot branch) (Win64, RelWithDebInfo, Static)
Connected players: 1. Characters in world: 52.
Connection peak: 1.
Server uptime: 23 minute(s) 36 second(s)
Update time diff: 16ms. Last 500 diffs summary:
|- Mean: 6ms
|- Median: 5ms
|- Percentiles (95, 99, max): 15ms, 16ms, 16ms
Using SSL version: OpenSSL 3.3.2 3 Sep 2024 (library: OpenSSL 3.3.2 3 Sep 2024)
Using Boost version: 1.81.0
Using CMake version: 3.30.3
Using MySQL version: 80039
Found MySQL Executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Compiled on: Windows 10.0.22631
Worldserver listening connections on port %hu
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in C:/Dev/WoW Server/Build/bin/RelWithDebInfo/Data/maps. Total size: 291014951 bytes
vmaps directory located in C:/Dev/WoW Server/Build/bin/RelWithDebInfo/Data/vmaps. Total size: 658130721 bytes
mmaps directory located in C:/Dev/WoW Server/Build/bin/RelWithDebInfo/Data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Using Playerbots DB Revision:
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: playerbots_names.sql
Latest WorldDatabase update: zz_optional_aq_quest_nerf.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
PlayerbotsDatabase queue size: 0
List of enabled modules:
|- mod-ah-bot
|- mod-autobalance
|- mod-individual-progression
|- mod-playerbots
|- mod-solo-lfg
|- mod-transmog

### Operating system

Windows 11 build 22631

### Custom changes or Modules

- Autobalance
- individualProgression
- Ahbot
- playerbots
- SoloLFG
- Transmog

**Comment by Nyeriah** [comment]
Individual progression requires you to complete the game step by step. This is caused by the individual progression module
