### ISSUE TITLE
conflict

### ISSUE THREAD

**Issue by luolingjun** [azerothcore/mod-solo-lfg#6]
https://github.com/azerothcore/azerothcore-wotlk/commit/a2b26272d28f137473c4e14841da0f042e3e8bdc

**Comment by locus313** [comment]
I can confirm the applying the patch not longer works.

```
error: patch failed: src/server/game/DungeonFinding/LFGMgr.cpp:27
error: src/server/game/DungeonFinding/LFGMgr.cpp: patch does not apply
error: patch failed: src/server/game/DungeonFinding/LFGQueue.cpp:289
error: src/server/game/DungeonFinding/LFGQueue.cpp: patch does not apply
```
Looks like the restyle commit mentioned by @luolingjun is what broke the patching from working.
